spring.application.name=SpringSecurity

# Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/security
spring.datasource.username=root
spring.datasource.password=root

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Server Port
server.port=61814

# JWT Configuration
app.jwt.secret=mySuperSecretKeyThatIsVeryLongAndSecureForJWTTokenGeneration12345
app.jwt.expiration=86400000